apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhdh-rc-17-go-github-jenkins-quay-r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhdh-rc-17-go-github-jenkins-quay-r 
  name: rhdh-rc-17-go-github-jenkins-quay-r
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhdh-rc-17-go-github-jenkins-quay-r
    weight: 100 
